---

- name: installing vsftpd package
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
    - vsftpd
    - libdb-utils

- name: "copying vsftpd systemd service file for {{ vsftpd_systemd_service_name }} instance"
  template:
    src: vsftpd.service.j2
    dest: /etc/systemd/system/vsftpd@{{ vsftpd_systemd_service_name }}.service
  when: vsftpd_systemd_service_name != 'vsftpd'
  
- name: "configuring systemd for {{ vsftpd_systemd_service_name }} instance"
  systemd: name=vsftpd@{{ vsftpd_systemd_service_name }} daemon_reload=yes enabled=yes
  when: vsftpd_systemd_service_name != 'vsftpd'

- name: configuring systemd for vsftpd
  systemd: name=vsftpd daemon_reload=yes enabled=yes
  when: vsftpd_systemd_service_name == 'vsftpd'
 
- name: configuring vsftpd instance
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: 0660
  notify:
    - restarting vsftpd service
  when: vsftpd_systemd_service_name == 'vsftpd'

- name: "creating {{ vsftpd_systemd_service_name }} configuration directory"
  file:
    state: directory
    path: "/etc/vsftpd/{{ vsftpd_systemd_service_name }}/"
  when: vsftpd_systemd_service_name != 'vsftpd'

- name: "configuring {{ vsftpd_systemd_service_name }} instance"
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/{{ vsftpd_systemd_service_name }}/vsftpd.conf
    owner: root
    group: root
    mode: 0750
  notify:
    - "restarting {{ vsftpd_systemd_service_name }} service"
  when: vsftpd_systemd_service_name != 'vsftpd'
