---
#- name: debug
#  debug:
#    msg: "{{ enable_local_users }}"

- name: installing vsftpd package
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
    - vsftpd
  
- name: configuring systemd for vsftpd
  systemd: name=vsftpd daemon_reload=yes enabled=yes
 
- name: configuring vsftpd instance
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: 0750
  notify:
    - restarting vsftpd service
